# =========================================
# Application Configuration
# =========================================

base.url=https://www.alfadock-pack.com

# =========================================
# Browser Configuration
# =========================================

browser=chrome
headless=false
slowmo=500
timeout=30000

# =========================================
# Company Login Credentials
# =========================================

company.username=testpro
company.password=testpro

#Ohkuma credentials
ohkuma.username=oaksystem
ohkuma.password=oak123

# =========================================
# User Login Credentials
# =========================================

user.username=admin
user.password=admin

ohkuma.user.username=admin
ohkuma.user.password=service701

# =========================================
# Screenshot Configuration
# =========================================

screenshot.on.failure=true
screenshot.path=test-output/screenshots

# =========================================
# Allure Configuration
# =========================================

allure.results.directory=target/allure-results

selectLanguage=English