name: Playwright Java Automation

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Compile test classes
        run: mvn test-compile

      - name: Install Playwright browsers
        shell: pwsh
        run: |
          mvn -q dependency:build-classpath -Dmdep.outputFile=cp.txt -Dmdep.includeScope=test
          $classpath = Get-Content cp.txt
          java -cp "target\classes;target\test-classes;$classpath" com.microsoft.playwright.CLI install

      - name: Run TestNG tests
        run: mvn clean test

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          if-no-files-found: warn